### ISSUE TITLE
Научиться пересобирать приложение в Spyder без его перезапуска

### ISSUE THREAD

**Issue by MargaritaLipatova** [MargaritaLipatova/Prorgams-text-to-docx#1]
Проблема: 
подправляешь функцию, запускаешь ТПО через F5(зеленый треугольник) в файле main_ishod-w.pyw,  изменение не применяется. 
Перезапускаешь spyder исправление в функции применяется.

**Comment by MargaritaLipatova** [comment]
Падает с ошибкой:
Reloaded modules: resources_rc, ui_files.ui_ishod_w, ui_files.ui_dialogChangeExtensions, dialog_ChangeExtensions, dialog_Ishod_w

**Comment by MargaritaLipatova** [comment]
Получилось без перезапуска заново запустить на исполнение код. Иногда происходит перезапуск ядра, но если заново запустить, то все хорошо.
Решение:
Инструменты -> Параметры -> Запуск -> Основные настройки  -> Удалить все переменные перед запуском

**Comment by Alex8BC** [comment]
Ошибка:
Reloaded modules: resources_rc, ui_files.ui_ishod_w, ui_files.ui_dialogChangeExtensions, dialog_ChangeExtensions, dialog_Ishod_w.

Решение (https://www.programmersought.com/article/61863877192/): 
Инструменты -> Параметры -> Интепретатор Python -> Перезагрузка модулей пользователя (UMR) -> Убрать галочку с пункта "Включить UMR"

**Comment by Alex8BC** [comment]
Решение:
Перейти на редактор Visual Studio Code.
